// Integration test: needs the local Supabase database (`pnpm db:start`).
// Checks that the hand-written Kysely types match the real schema.
import { afterAll, describe, expect, it } from "vitest";
import { createDb, sql } from "./index.ts";

const db = createDb({
  connectionString: process.env.TEST_DATABASE_URL ?? "postgresql://postgres:postgres@127.0.0.1:54322/postgres",
  max: 2,
});

afterAll(() => db.destroy());

// Column names per table as declared in types.ts.
const declared: Record<string, string[]> = {
  grader_suites: [
    "id",
    "institution_id",
    "key",
    "version",
    "title",
    "path",
    "git_ref",
    "stack_profile_id",
    "manifest",
    "status",
    "created_at",
  ],
  evaluation_runs: [
    "id",
    "institution_id",
    "submission_id",
    "sha",
    "trigger",
    "status",
    "grader_suite_id",
    "stack_profile_id",
    "score",
    "summary",
    "error",
    "requested_by",
    "callback_token_hash",
    "gh_workflow_run_id",
    "check_run_id",
    "queued_at",
    "dispatched_at",
    "started_at",
    "finished_at",
  ],
  test_results: [
    "id",
    "institution_id",
    "run_id",
    "stage",
    "test_key",
    "title",
    "category",
    "status",
    "weight",
    "duration_ms",
    "expected",
    "actual",
    "message",
    "hint",
    "evidence",
    "attachments",
    "staff_notes",
  ],
  commits: [
    "id",
    "institution_id",
    "repository_id",
    "sha",
    "branch",
    "message",
    "authored_at",
    "pushed_at",
    "author_login",
    "author_github_id",
    "author_profile_id",
    "details_status",
    "parent_count",
    "additions",
    "deletions",
    "files_changed",
    "effective_lines",
    "is_bot",
    "created_at",
  ],
  pull_requests: [
    "id",
    "institution_id",
    "repository_id",
    "number",
    "github_id",
    "author_github_id",
    "author_profile_id",
    "title",
    "body_length",
    "linked_issues",
    "state",
    "review_count",
    "opened_at",
    "closed_at",
    "merged_at",
    "updated_at",
  ],
  pr_reviews: [
    "id",
    "institution_id",
    "repository_id",
    "pr_number",
    "github_review_id",
    "reviewer_github_id",
    "reviewer_profile_id",
    "state",
    "submitted_at",
  ],
  issues: [
    "id",
    "institution_id",
    "repository_id",
    "number",
    "github_id",
    "author_github_id",
    "author_profile_id",
    "title",
    "state",
    "opened_at",
    "closed_at",
    "updated_at",
  ],
  process_snapshots: [
    "id",
    "institution_id",
    "submission_id",
    "score",
    "breakdown",
    "policy",
    "is_final",
    "computed_at",
  ],
  stack_profiles: [
    "id",
    "institution_id",
    "key",
    "version",
    "display_name",
    "description",
    "definition",
    "status",
    "created_at",
  ],
  assignments: [
    "id",
    "institution_id",
    "course_id",
    "slug",
    "title",
    "spec_md",
    "stack_profile_id",
    "template_repo",
    "release_at",
    "due_at",
    "late_policy",
    "weights",
    "process_policy",
    "triggers",
    "run_quota_per_day",
    "grader_suite_id",
    "status",
    "published_at",
    "grades_released_at",
    "regrade_window_days",
    "stage_settings",
    "created_by",
    "created_at",
    "updated_at",
  ],
  assignment_criteria: [
    "id",
    "institution_id",
    "assignment_id",
    "title",
    "description",
    "max_points",
    "position",
    "created_at",
  ],
  assignment_extensions: [
    "id",
    "institution_id",
    "assignment_id",
    "user_id",
    "due_at",
    "reason",
    "granted_by",
    "created_at",
  ],
  repositories: [
    "id",
    "institution_id",
    "github_installation_id",
    "owner",
    "name",
    "github_repo_id",
    "default_branch",
    "private",
    "archived",
    "head_sha",
    "head_pushed_at",
    "start_sha",
    "created_at",
    "updated_at",
  ],
  submissions: [
    "id",
    "institution_id",
    "assignment_id",
    "user_id",
    "repository_id",
    "status",
    "status_detail",
    "provisioning_attempts",
    "final_sha",
    "submitted_at",
    "late_days",
    "finalized_at",
    "grade_released_at",
    "created_at",
    "updated_at",
  ],
  rubric_scores: [
    "id",
    "institution_id",
    "submission_id",
    "criterion_id",
    "points",
    "comment",
    "scored_by",
    "scored_at",
  ],
  feedback: ["id", "institution_id", "submission_id", "body_md", "author_id", "updated_at"],
  grades: [
    "id",
    "institution_id",
    "submission_id",
    "user_id",
    "version",
    "evaluation_run_id",
    "components",
    "late_days",
    "late_penalty",
    "computed_score",
    "override_score",
    "override_reason",
    "final_score",
    "complete",
    "is_current",
    "released_at",
    "created_by",
    "created_at",
  ],
  grade_reports: [
    "id",
    "institution_id",
    "submission_id",
    "grade_id",
    "user_id",
    "version",
    "grade_version",
    "json_path",
    "pdf_path",
    "sha256",
    "pdf_sha256",
    "generated_at",
  ],
  submission_snapshots: [
    "id",
    "institution_id",
    "submission_id",
    "run_id",
    "sha",
    "bundle_path",
    "bundle_sha256",
    "bundle_size",
    "tarball_path",
    "tarball_sha256",
    "tarball_size",
    "created_at",
  ],
  notifications: [
    "id",
    "institution_id",
    "user_id",
    "type",
    "title",
    "body",
    "link",
    "dedupe_key",
    "created_at",
    "read_at",
  ],
  lms_connections: [
    "id",
    "institution_id",
    "type",
    "name",
    "status",
    "issuer",
    "client_id",
    "deployment_ids",
    "auth_login_url",
    "auth_token_url",
    "jwks_url",
    "registration",
    "registered_by",
    "created_by",
    "created_at",
    "updated_at",
  ],
  lms_user_links: [
    "id",
    "institution_id",
    "lms_connection_id",
    "lms_user_id",
    "profile_id",
    "email",
    "name",
    "matched_by",
    "status",
    "last_launch_at",
    "created_at",
  ],
  lms_course_links: [
    "id",
    "institution_id",
    "lms_connection_id",
    "context_id",
    "context_title",
    "course_id",
    "nrps_url",
    "ags_lineitems_url",
    "linked_by",
    "created_at",
    "updated_at",
    "roster_synced_at",
    "roster_summary",
    "google_account_id",
  ],
  lms_assignment_links: [
    "id",
    "institution_id",
    "assignment_id",
    "lms_course_link_id",
    "resource_link_id",
    "lineitem_url",
    "score_maximum",
    "created_by",
    "created_at",
    "updated_at",
    "classroom_coursework_id",
    "classroom_link",
  ],
  google_accounts: [
    "id",
    "institution_id",
    "profile_id",
    "google_user_id",
    "email",
    "refresh_token_encrypted",
    "scopes",
    "connected_at",
    "revoked_at",
    "last_error",
  ],
  google_oauth_states: ["state", "institution_id", "profile_id", "code_verifier", "next", "created_at", "consumed_at"],
  lms_grade_syncs: [
    "id",
    "institution_id",
    "grade_id",
    "submission_id",
    "lms_assignment_link_id",
    "lms_user_id",
    "status",
    "score_given",
    "lms_score",
    "attempts",
    "last_error",
    "synced_at",
    "checked_at",
    "created_at",
    "updated_at",
  ],
  lti_deep_link_requests: [
    "id",
    "token_hash",
    "lms_connection_id",
    "lms_course_link_id",
    "profile_id",
    "deployment_id",
    "return_url",
    "data",
    "accept_multiple",
    "expires_at",
    "used_at",
    "created_at",
  ],
  lti_launch_states: ["state", "nonce", "lms_connection_id", "created_at", "consumed_at"],
  lti_registration_invites: [
    "id",
    "institution_id",
    "token_hash",
    "type",
    "name",
    "created_by",
    "expires_at",
    "used_at",
    "lms_connection_id",
    "created_at",
  ],
  replicated_objects: ["bucket", "path", "institution_id", "size", "locked_until", "replicated_at"],
  record_exports: [
    "id",
    "institution_id",
    "requested_by",
    "status",
    "location",
    "path",
    "size",
    "sha256",
    "files",
    "error",
    "created_at",
    "finished_at",
  ],
  run_artifacts: ["id", "institution_id", "run_id", "name", "path", "content_type", "size", "expires_at", "created_at"],
  regrade_requests: [
    "id",
    "institution_id",
    "submission_id",
    "requested_by",
    "message",
    "status",
    "response",
    "resolved_by",
    "resolved_at",
    "created_at",
    "updated_at",
  ],
  review_comments: [
    "id",
    "institution_id",
    "submission_id",
    "sha",
    "path",
    "line",
    "body",
    "author_id",
    "created_at",
    "updated_at",
  ],
  branch_pushes: [
    "id",
    "institution_id",
    "repository_id",
    "sha",
    "pushed_at",
    "pusher_github_id",
    "by_bot",
    "forced",
    "received_at",
  ],
  platform_settings: ["key", "value", "description", "updated_by", "updated_at"],
  email_outbox: [
    "id",
    "institution_id",
    "to_email",
    "template",
    "payload",
    "status",
    "attempts",
    "last_error",
    "created_at",
    "sent_at",
  ],
  institutions: [
    "id",
    "name",
    "slug",
    "status",
    "limits",
    "settings",
    "contract_started_at",
    "contract_ended_at",
    "purge_after",
    "created_by",
    "created_at",
    "updated_at",
  ],
  profiles: [
    "id",
    "email",
    "full_name",
    "avatar_url",
    "github_user_id",
    "github_login",
    "status",
    "anonymised_at",
    "email_notification_types",
    "created_at",
    "updated_at",
  ],
  user_roles: ["user_id", "role", "granted_by", "created_at"],
  institution_memberships: [
    "id",
    "institution_id",
    "user_id",
    "role",
    "status",
    "external_id",
    "created_at",
    "updated_at",
  ],
  courses: [
    "id",
    "institution_id",
    "code",
    "name",
    "term",
    "timezone",
    "archived_at",
    "github_installation_id",
    "created_by",
    "created_at",
    "updated_at",
  ],
  course_memberships: [
    "id",
    "institution_id",
    "course_id",
    "user_id",
    "role",
    "section",
    "source",
    "created_at",
    "updated_at",
  ],
  invitations: [
    "id",
    "institution_id",
    "email",
    "github_login",
    "role",
    "course_id",
    "course_role",
    "token_hash",
    "invited_by",
    "expires_at",
    "accepted_at",
    "accepted_by",
    "created_at",
  ],
  audit_logs: ["id", "institution_id", "actor_id", "action", "entity", "entity_id", "before", "after", "ip", "at"],
  github_installations: [
    "id",
    "institution_id",
    "installation_id",
    "account_id",
    "account_login",
    "account_type",
    "repository_selection",
    "permissions",
    "events",
    "suspended_at",
    "deleted_at",
    "linked_at",
    "linked_by",
    "created_at",
    "updated_at",
  ],
  github_link_requests: [
    "id",
    "institution_id",
    "requested_by",
    "github_user_id",
    "expires_at",
    "completed_at",
    "installation_id",
    "created_at",
  ],
  github_events: [
    "id",
    "delivery_id",
    "event",
    "action",
    "installation_id",
    "institution_id",
    "repository_full_name",
    "sender_id",
    "payload",
    "received_at",
    "processed_at",
    "attempts",
    "error",
  ],
};

describe("Kysely types match the database", () => {
  it("covers every public table, and every column exists in both", async () => {
    const { rows } = await sql<{ table_name: string; column_name: string }>`
      select table_name, column_name from information_schema.columns
      where table_schema = 'public' and table_name in (
        select tablename from pg_tables where schemaname = 'public')
      order by table_name, ordinal_position`.execute(db);

    const actual: Record<string, string[]> = {};
    for (const r of rows) (actual[r.table_name] ??= []).push(r.column_name);

    expect(Object.keys(actual).sort()).toEqual(Object.keys(declared).sort());
    for (const [table, columns] of Object.entries(declared)) {
      expect(actual[table]?.slice().sort(), table).toEqual(columns.slice().sort());
    }
  });

  it("returns int8 columns as numbers", async () => {
    const { rows } = await sql<{ n: number }>`select 9007199254740991::int8 as n`.execute(db);
    expect(rows[0]?.n).toBe(Number.MAX_SAFE_INTEGER);
    await expect(sql`select 9007199254740993::int8 as n`.execute(db)).rejects.toThrow(RangeError);
  });
});
